# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

  PROJECT="rabbitmq_v1"
  RMQIP="192.168.50.123"


  config.vm.box_version = "1707.01 "
  config.vm.box = "centos/7"
  config.ssh.insert_key = true

  config.vm.box = "centos/7"

  config.vm.network "forwarded_port", guest: 5672, host: 5672
  config.vm.network "forwarded_port", guest: 15672, host: 15672

  config.vm.define :rmq do |rmq|
    rmq.vm.hostname = "rmqv1.host1"
    rmq.vm.network :private_network, ip: "#{RMQIP}"
    rmq.vm.provision :shell, :path => ".provision/rmq_bootstrap.sh"
    rmq.vm.provider "virtualbox" do |vb|
      vb.cpus = "2"
      vb.memory = "2048"
    end
  end

end

